### ISSUE TITLE
Project Section changes

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#13]
### Few suggestions 

- Either add image or remove it. If you don't find relevant image, chuck the idea of adding image.

- Remove `view` button as we don't have anything to link.

#### @ShreyaAnand, what say?

**Comment by ShreyaAnand** [comment]
Yeah this idea is ok!!

**Comment by ArpitKotecha** [comment]
Should I go ahead and remove image as well as view element.

**Comment by vinitshahdeo** [comment]
Yeah, definitely!
 As of now remove these, later we can add!
**Make the changes and send PR.**

**Comment by ArpitKotecha** [comment]
Done!
