### ISSUE TITLE
Change OG image

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#17]
Currently, the logo is being used as OG image. 

**Ask @pvsmounish to design an attractive background image which will be used as OG image for the official website.** 

Once done, update and send PR.
@ArpitKotecha @ShreyaAnand

**Comment by ArpitKotecha** [comment]
@pvsmounish Please send the new OG Image.

**Comment by vinitshahdeo** [comment]
@ArpitKotecha Check the WhatsApp Group. @pvsmounish has designed it. 
**Please make the changes create the PR.**
