### ISSUE TITLE
Add Past Events Section

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#23]
**As the VinHack is over so remove the `register now` link!**

- Add a section for Past Events. 
- Mention [VinHack](https://vinhack.vinnovateit.com/) and Orientation Session there. 
- Add a **slideshow(gallery)** for VinHack. Choose few good images from [here](https://drive.google.com/open?id=1HMnmCmKHT4gjMjdjwJR0MGtvCaSwyNVl).
- Put the [link]() to the official repository of VinHack.

<img width="1196" alt="Screenshot 2019-03-26 at 6 11 12 PM" src="https://user-images.githubusercontent.com/20594326/54998348-f0604900-4ff3-11e9-9676-f5f07a68a305.png">

**Comment by ArpitKotecha** [comment]
@vinitshahdeo @ShreyaAnand From where/whom I can get the content

**Comment by vinitshahdeo** [comment]
Tell me your mail id, I'll send you the details.

**Comment by ArpitKotecha** [comment]
> Tell me your mail id, I'll send you the details.

arpitjain7074@gmail.com

**Comment by vinitshahdeo** [comment]
Mailed you. Please check!!

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 
Any update on this?

**Comment by ArpitKotecha** [comment]
@vinitshahdeo 
Got stuck in DA's & lab CAT's will do by month end.

**Comment by vinitshahdeo** [comment]
It's okay @ArpitKotecha !

Finally the PR is merged.
