### ISSUE TITLE
Redefining TEAM section

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#28]
#### Let's divide the TEAM `<section></section>` into three parts -

**1. Advisory Board
2. Ex-board
3. Current board**

Just change current board members to ex-board members. Get the current board members details from Meet and update it.

For Advisory board, Add following members : 

**1. [Sachin Vasistha](https://www.linkedin.com/in/sachinvasista/) (Founder)
2. [Sulabh Agarwal](https://www.facebook.com/sulabh.agarwal.522)(President 2015-16)
3. [Apoorv Bandi](https://www.facebook.com/apoorv.bandi)(President 2016-17)
4. [Vinit Shahdeo](https://www.facebook.com/vinit.shahdeo)(President 2017-18)**

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Could you please send or tell me from where to get other details of advisory board members such as github, linkedIn, insta id as well as their pics.

**Comment by vinitshahdeo** [comment]
Just google all the names, I hope you'll get the details. 
For specific results just add *VIT* as keyword. Use their LinkedIn/GitHub profile pictures.

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 
Any updates on this?

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Didn't get the details from all board members yet.

**Comment by vinitshahdeo** [comment]
Ask Meet. He'll remind others.
This is the probably last issue before FAT.

**Comment by ArpitKotecha** [comment]
> Ask Meet. He'll remind others.
> This is the probably last issue before FAT.

Did that. Roshan bhaiya messaged me regarding this. Will update by tomorrow.

**Comment by ArpitKotecha** [comment]
@vinitshahdeo How's the new design?
![Board Member Section Screenshot](https://firebasestorage.googleapis.com/v0/b/creditmine-002.appspot.com/o/Capture.PNG?alt=media&token=d7e2d9da-ba96-4d35-905f-2eb486ee2888)

**Comment by vinitshahdeo** [comment]
> @vinitshahdeo How's the new design?
> 
> ![Board Member Section Screenshot](https://camo.githubusercontent.com/8fd5ec0f91f8d4729bacc8a08fd84d57db463f35/68747470733a2f2f666972656261736573746f726167652e676f6f676c65617069732e636f6d2f76302f622f76696e6e6f7661746569742d3030312e61707073706f742e636f6d2f6f2f436170747572652e504e473f616c743d6d6564696126746f6b656e3d38313565633037642d653839642d346136332d383135352d366230663639306637396265)

Mind blowing @ArpitKotecha !
This is something I wanted :)

**Awesome work! I highly appreciate it!**

**Comment by vinitshahdeo** [comment]
@ShreyaAnand 

See the changes : [vinnovateit.com](https://vinnovateit.com/) 

Post your review!

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 

It's working locally but the CSS is not loaded after deployment. Please fix it!

<img width="1133" alt="Screenshot 2019-04-06 at 3 07 32 AM" src="https://user-images.githubusercontent.com/20594326/55657856-3fd71e00-5819-11e9-977d-15ebee26f162.png">

**Comment by ArpitKotecha** [comment]
@vinitshahdeo 

> @ArpitKotecha
> 
> It's working locally but the CSS is not loaded after deployment. Please fix it!
> 
> <img alt="Screenshot 2019-04-06 at 3 07 32 AM" width="1133" src="https://user-images.githubusercontent.com/20594326/55657856-3fd71e00-5819-11e9-977d-15ebee26f162.png">

@vinitshahdeo It's working on the deployed version too. Would check again.

**Comment by vinitshahdeo** [comment]
Yeah, it's working!
