### ISSUE TITLE
SEO Changes

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#4]
Run a **SEO test** and make the suggested changes for the same.

- Make sure that there should not be any **broken** links
- **Meta tags** are missing, add those!
- Add `robots.txt`

@ShreyaAnand

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 
### Make the SEO changes. Add all the `<meta .../>` tags!

**Comment by ArpitKotecha** [comment]
> @ArpitKotecha
> 
> ### Make the SEO changes. Add all the `<meta .../>` tags!

Done!

**Comment by ArpitKotecha** [comment]
@ArpitKotecha Our Seo score according to google lighthouse is 100.

**Comment by vinitshahdeo** [comment]
That's great @ArpitKotecha !

I'll assign few more tasks soon.
