### ISSUE TITLE
Project Section Changes

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinnovateIT-Website#5]
### Projects `<section>.....</section>` is incomplete.

**Please make the following changes -**

- Add relevant **images**.
- Fix the **broken links**
- Add **1-2 lines of brief description** for each project

**Comment by ArpitKotecha** [comment]
Do we have content available?

**Comment by vinitshahdeo** [comment]
> Do we have content available?

**Yes, tell me your mail id?**
I'll forward you few project reports. Add any six!

**Comment by ArpitKotecha** [comment]
arpitjain7074@gmail.com

**Comment by ArpitKotecha** [comment]
It's arpitjain7074@gmail.com

**Comment by vinitshahdeo** [comment]
> It's [arpitjain7074@gmail.com](mailto:arpitjain7074@gmail.com)

Forwarded you the reports! **Please check and update it.**

**Comment by ArpitKotecha** [comment]
Got the reports. Would update by tomorrow.

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 
Try to get **relevant image** from `google search`!
